{% set data = load_setup_py_data() %}

package:
  name: niaaml
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python>=3.6.1
    - numpy>=1.19.1
    - scikit-learn>=0.23.2
    - NiaPy
    - pandas>=1.1.4

  run:
    - python>=3.6.1
    - numpy>=1.19.1
    - scikit-learn>=0.23.2
    - NiaPy
    - pandas>=1.1.4

test:
  imports:
    - niaaml

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}