name: publish_conda

on: [release]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: publish-to-conda
      uses: amauryval/publish_conda_package_action@1.0.0
      with:
        CondaDir: 'conda'
        Channels: 'conda-forge niaorg/label/rc'
        Platforms: 'osx-64 linux-32 linux-64 win-32 win-64'
        CondaUsername: ${{ secrets.CONDA_USERNAME }}
        CondaPassword: ${{ secrets.CONDA_PASSWORD }}